name: Build

on:
  push:
    branches: [ Dev, dev, main, feature/** ]
  pull_request:
    branches: [ Dev, dev, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install compiler & deps (cmake + raylib deps)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake make g++ \
            libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev \
            libgl1-mesa-dev mesa-common-dev libasound2-dev libpulse-dev \
            libudev-dev libdrm-dev libgbm-dev

      - name: Build (Makefile)
        run: |
          make clean || true
          make -j"$(nproc)" build-all