name: C++ Lint • Build • Test

on:
  push:
    branches: [ Dev,dev, main, feature/** ]
  pull_request:
    branches: [ Dev,dev, main ]

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: true

      - name: Install compiler & deps (cmake + raylib deps)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake make g++ cppcheck clang-format \
            libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev \
            libgl1-mesa-dev mesa-common-dev libasound2-dev libpulse-dev \
            libudev-dev libdrm-dev libgbm-dev

      - name: Lint (cppcheck)
        run: cppcheck --enable=all --inconclusive --std=c++17 --force --error-exitcode=1 -I include src tests

      - name: clang-format (check only)
        run: |
          files=$(find include src tests -type f \( -name '*.h' -o -name '*.hpp' -o -name '*.cpp' \))
          if [ -n "$files" ]; then
            for f in $files; do
              diff -u "$f" <(clang-format "$f") || { echo "::error file=$f::Run clang-format and commit"; exit 1; }
            done
          fi

      - name: Build (Makefile)
        run: |
          make clean || true
          make -j"$(nproc)" build-all

      - name: Run unit tests
        run: make -j"$(nproc)" test
