name: Doxygen Docs

on:
  push:
    branches: [ main ]

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Doxygen & Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz
      - name: Generate docs
        run: |
          if [ -f Doxyfile ]; then
            doxygen Doxyfile
          else
            echo "::warning ::No Doxyfile found. Skipping."
            exit 0
          fi
      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-html
          path: docs/html
          if-no-files-found: ignore

          
